#---
# Items that apply to ALL profiles:
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/

# eureka:
#   client:   
#     serviceUrl:
#       defaultZone: http://peer-1-server.com:9001/eureka, http://peer-2-server.com:9002/eureka, http://peer-3-server.com:9003/eureka

---
#   spring:
#     profiles: primary

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-terciary:8013/eureka/

#   server:
#     port: 8011

# ---
#   spring:
#     profiles: secondary

#   eureka:
#     client:
#       serviceUrl:
#         defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/

#   server:
#     port: 8012

# ---
#   spring:
#     profiles: tertiary

#   eureka:
#     client:
#       serviceUrl:
#         defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secundary:8012/eureka/

#   server:
#     port: 8013

      
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
